### ISSUE TITLE
"csv-paste line-number" always says "unexpected end of file"

### ISSUE THREAD

**Issue by davidfisher71** [acfr/comma#39]
Example:

$ echo -e "1,2\n3,4\n5,6" > eg.csv
$ cat eg.csv | csv-to-bin ui,ui > eg.bin
$ csv-paste line-number "eg.bin;binary=ui,ui" > out.bin
(prints "csv-paste: unexpected end of file in eg.csv;binary=ui,ui")

$ cat out.bin | csv-from-bin ui,ui,ui
0,1,2
1,3,4
2,5,6
(still works successfully)

**Comment by mimhoff** [comment]
This caused a problem for me last week -- the error code caused some things later in the pipeline to not execute, even though the output was correct.

So csv-paste should now exit with this error when one stream (stdin or file) ends before another stream. line-number and value do not affect this.
