### ISSUE TITLE
csv-shuffle: --input-fields option for ease of use

### ISSUE THREAD

**Issue by junderwood** [acfr/comma#53]
currently the args are --fields and --output-fields.
if you do the following:
echo 1,2,3 | csv-shuffle --input-fields=a,b,c --output-fields=a,b
you get the error:
csv-shuffle: "a" not found in input fields
the correct usage is:
echo 1,2,3 | csv-shuffle --fields=a,b,c --output-fields=a,b
but it might be nice to support --input-fields as well as fields

**Comment by vlaskine** [comment]
a bit redundant, but done
