### ISSUE TITLE
csv-select: --from and --to don't work as expected (for times at least)

### ISSUE THREAD

**Issue by junderwood** [acfr/comma#54]
echo -e "20141001T052130.337607\n20141001T052130.470983\n20141001T052130.604360\n20141001T052130.737613" | csv-select --fields=t "t;from=20141001T052130.4" "t;to=20141001T052130.65"

gives the expected output:
20141001T052130.470983
20141001T052130.604360

However, using --from and --to as the help suggests:
echo -e "20141001T052130.337607\n20141001T052130.470983\n20141001T052130.604360\n20141001T052130.737613" | csv-select --fields=t --from=20141001T052130.4 --to=20141001T052130.65
gives the error:
csv-select: caught: bad lexical cast: source type value could not be interpreted as target

I probably wouldn't mind if the --from --to option was removed and we always have to say "field;compare=blah"... but either way I think there is a mismatch now between the help and the reality. I might have missed something obvious though...

**Comment by vlaskine** [comment]
it's fixed, thanks for spotting it
