### ISSUE TITLE
csv-time: inaccurate time conversion

### ISSUE THREAD

**Issue by mikkelkh** [acfr/comma#58]
I have a problem with the precision of time conversion using csv-time.

Simple example:

echo 20130521T234010.752231 | csv-time --from=iso --to=seconds | csv-time --from=seconds --to=iso

returns "20130521T234010.752230" (off by one micro-second).

**Comment by vlaskine** [comment]
@mikkelkh: thank you for pointing out

the fix is pushed, please pull, build, and install comma
