### ISSUE TITLE
windows build errors: latest summary

### ISSUE THREAD

**Issue by junderwood** [acfr/comma#59]
Not a priority, but while I have them handy, here they are:

Summary:
Error	1	error C1083: Cannot open include file: 'sys/ioctl.h': No such file or directory	C:\Users\j.underwood\Code\cpp\source\comma\io\stream.cpp	41
Error	2	error C2039: 'round' : is not a member of '`global namespace''	C:\Users\j.underwood\Code\cpp\source\comma\csv\applications\csv-time.cpp	199
Error	3	error C3861: 'round': identifier not found	C:\Users\j.underwood\Code\cpp\source\comma\csv\applications\csv-time.cpp	199
Error	4	error C1083: Cannot open include file: 'sysexits.h': No such file or directory	C:\Users\j.underwood\Code\cpp\source\comma\csv\applications\csv-blocks.cpp	44
Error	5	error C2899: typename cannot be used outside a template declaration	C:\Users\j.underwood\Code\cpp\source\comma\csv\applications\csv-sort.cpp	194
Error	6	error C2899: typename cannot be used outside a template declaration	C:\Users\j.underwood\Code\cpp\source\comma\csv\applications\csv-sort.cpp	250
Error	7	error C2899: typename cannot be used outside a template declaration	C:\Users\j.underwood\Code\cpp\source\comma\csv\applications\csv-sort.cpp	260
Error	8	error C2899: typename cannot be used outside a template declaration	C:\Users\j.underwood\Code\cpp\source\comma\csv\applications\csv-sort.cpp	268

Full build output:
4>ClCompile:
4>  stream.cpp
4>..\..\..\..\source\comma\io\stream.cpp(41): fatal error C1083: Cannot open include file: 'sys/ioctl.h': No such file or directory

6>ClCompile:
6>  csv-time.cpp
6>..\..\..\..\..\source\comma\csv\applications\csv-time.cpp(199): error C2039: 'round' : is not a member of '`global namespace''
6>..\..\..\..\..\source\comma\csv\applications\csv-time.cpp(199): error C3861: 'round': identifier not found

8>ClCompile:
8>  csv-blocks.cpp
8>..\..\..\..\..\source\comma\csv\applications\csv-blocks.cpp(44): fatal error C1083: Cannot open include file: 'sysexits.h': No such file or directory

7>ClCompile:
7>  csv-sort.cpp
7>..\..\..\..\..\source\comma\csv\applications\csv-sort.cpp(194): error C2899: typename cannot be used outside a template declaration
7>..\..\..\..\..\source\comma\csv\applications\csv-sort.cpp(250): error C2899: typename cannot be used outside a template declaration
7>..\..\..\..\..\source\comma\csv\applications\csv-sort.cpp(260): error C2899: typename cannot be used outside a template declaration
7>..\..\..\..\..\source\comma\csv\applications\csv-sort.cpp(268): error C2899: typename cannot be used outside a template declaration

**Comment by vlaskine** [comment]
hopefully fixed most of them

the failure in csv-time is inexplicable, since ::round() is a part of STL and according to the documentation is meant to come from #include <cmath>

you can try to include math.h instead to see whether it fixes the problem

could you please keep posting further build failures, i will try fix them immediately: the alternative is to wait indefinitely until i have time and guts to install and run windows virtual box

**Comment by junderwood** [comment]
Thanks seva,

The round prob is there with math.h too for some reason.
Also, I seemed to get some new ones:

6>ClCompile:
6>  csv-blocks.cpp
5>ClCompile:
5>  csv-time.cpp
5>..\..\..\..\..\source\comma\csv\applications\csv-time.cpp(199): error C2039: 'round' : is not a member of '`global namespace''
5>..\..\..\..\..\source\comma\csv\applications\csv-time.cpp(199): error C3861: 'round': identifier not found
6>..\..\..\..\..\source\comma\csv\applications\csv-blocks.cpp(275): error C2065: 'EX_NOINPUT' : undeclared identifier
6>..\..\..\..\..\source\comma\csv\applications\csv-blocks.cpp(299): error C2065: 'ssize_t' : undeclared identifier
6>..\..\..\..\..\source\comma\csv\applications\csv-blocks.cpp(299): error C2146: syntax error : missing ';' before identifier 'bytes_read'
6>..\..\..\..\..\source\comma\csv\applications\csv-blocks.cpp(299): error C2065: 'bytes_read' : undeclared identifier
6>..\..\..\..\..\source\comma\csv\applications\csv-blocks.cpp(299): error C2039: 'getline' : is not a member of '`global namespace''
6>..\..\..\..\..\source\comma\csv\applications\csv-blocks.cpp(299): error C3861: 'getline': identifier not found
6>..\..\..\..\..\source\comma\csv\applications\csv-blocks.cpp(300): error C2065: 'bytes_read' : undeclared identifier
6>..\..\..\..\..\source\comma\csv\applications\csv-blocks.cpp(300): error C2065: 'EX_NOINPUT' : undeclared identifier
6>..\..\..\..\..\source\comma\csv\applications\csv-blocks.cpp(305): error C2065: 'bytes_read' : undeclared identifier
6>..\..\..\..\..\source\comma\csv\applications\csv-blocks.cpp(306): error C2065: 'bytes_read' : undeclared identifier
6>..\..\..\..\..\source\comma\csv\applications\csv-blocks.cpp(307): error C2065: 'bytes_read' : undeclared identifier
6>..\..\..\..\..\source\comma\csv\applications\csv-blocks.cpp(308): error C2065: 'bytes_read' : undeclared identifier
6>..\..\..\..\..\source\comma\csv\applications\csv-blocks.cpp(308): error C2065: 'bytes_read' : undeclared identifier

**Comment by vlaskine** [comment]
fixed, please try again

please close the ticket, if compilation is fixed

if not, please paste the error output here

**Comment by junderwood** [comment]
thanks, that worked, good old ::ceil !
